@baseAdress = http://localhost:5038
@courseId=3fa85f64-5717-4562-b3fc-2c963f66afa6
Post {{baseAdress}}/api/v1/baskets/item
Content-Type: application/json  
Accept: application/json
{
    "courseId":"{{courseId}}",
    "courseName": "ömer1",
    "coursePrice": 110
}
###
DELETE {{baseAdress}}/api/v1/baskets/item/{{courseId}}
Accept: application/json
Content-Type: application/json
###
    