@baseAdress = http://localhost:5038
@courseId=3fa85f64-5717-4562-b3fc-2c963f66afa6


GET {{baseAdress}}/api/v1/baskets/user
Accept: application/json
###
Post {{baseAdress}}/api/v1/baskets/item
Content-Type: application/json  
Accept: application/json
{
    "courseId":"{{courseId}}",
    "courseName": "ömer1",
    "coursePrice": 30
}
###
DELETE {{baseAdress}}/api/v1/baskets/item/{{courseId}}
Accept: application/json
Content-Type: application/json
###
Put {{baseAdress}}/api/v1/baskets/apply-discount-coupon
Content-Type: application/json  
Accept: application/json
{
    "coupon":"abcdef",
    "discountrate": 0.2   
}
###
delete {{baseAdress}}/api/v1/baskets/remove-discount-coupon
Accept: application/json
###