@baseAdtess = http://localhost:5038

Post {{baseAdtess}}/api/v1/baskets/item
Content-Type: application/json  
Accept: application/json
{
    "courseId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "courseName": "ömer1",
    "coursePrice": 110
}
###
    