@baseAddres = http://localhost:5158
@categoryId = 08de6958-7534-fa1d-50a1-3236bc3b0000
@courseId=08de6e1b-58ad-4d90-50a1-3236bc3b0000
GET {{baseAddres}}/api/categories
Accept: application/json
###
POST {{baseAddres}}/api/categories
Accept: application/json
Content-Type:application/json
{
  "name" : "Category1"
}
###
GET {{baseAddres}}/api/categories/{{categoryId}}
Accept: application/json
###
POST {{baseAddres}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "name": "Course12",
  "description": "Course1 Description",
  "price": 100,
  "imageUrl": "https://example.com/picture.jpg",
  "categoryId": "{{categoryId}}"
}
###
GET {{baseAddres}}/api/courses
Accept: application/json
###
GET {{baseAddres}}/api/courses/{{courseId}}
Accept: application/json