@baseAddres = http://localhost:5158

GET {{baseAddres}}/api/categories
Accept: application/json
###
POST {{baseAddres}}/api/categories
Accept: application/json
Content-Type:application/json
{
  "name" : "Category1"
}
###