@baseAddres = http://localhost:5158
@categoryId = 08de6958-7534-fa1d-50a1-3236bc3b0000
@courseId=08de6e1b-58ad-4d90-50a1-3236bc3b0000
@userId=bc3b0000-3236-50a1-4116-08de7084ba8e
GET {{baseAddres}}/api/v1.0/categories
Accept: application/json
###
POST {{baseAddres}}/api/categories
Accept: application/json
Content-Type:application/json
{
  "name" : "Category1"
}
###
GET {{baseAddres}}/api/categories/{{categoryId}}
Accept: application/json
###
POST {{baseAddres}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "name": "Course12",
  "description": "Course1 Description",
  "price": 100,
  "imageUrl": "https://example.com/picture.jpg",
  "categoryId": "{{categoryId}}"
}
###
PUT {{baseAddres}}/api/courses
Accept: application/json
Content-Type: application/json
{
  "Id": "{{courseId}}",
  "name": "Course12 ömer",
  "description": "Course1 Description : deðiþen kurs",
  "price": 10320,
  "imageUrl": "https://example.com/picture2332.jpg",
  "categoryId": "{{categoryId}}"
}
###
GET {{baseAddres}}/api/courses
Accept: application/json
###
GET {{baseAddres}}/api/courses/{{courseId}}
Accept: application/json
###
DELETE {{baseAddres}}/api/courses/{{courseId}}
Accept: application/json
###
Get {{baseAddres}}/api/courses/user/{{userId}}
Accept: application/json
###


