@baseAdress = http://localhost:5269
###
post {{baseAdress}}/api/v1/files; boundary=---WebKitFormBoundary

-----WebKitFormBoundary
ContentDisposition: form-data; name="file"; filename="hello-word.txt"
content-type :multipart/form-data
-----WebKitFormBoundary--
###


